version: 1.0.{build}
os: Visual Studio 2015 RC
environment:
  webdeploy_site: 
    secure: 3ncx3RGVt/3/LIGMAtN79g==
  webdeploy_url:
    secure: Oo/VZhq9pfkDjL2ij3KtWGq7qQdvkqYoBUrYipAxrGCfFLtKgJzjXMfwKNVey4c/P8ScowY/h3nnSD9B3nxOI647Xr9Zi3FEEoVxwoJte7U=
  webdeploy_user: 
    secure: VHtnliksXJA/8h80qhGVhA==
  webdeploy_password: 
    secure: kxx9bP3x1UznwYRxeDeprwBLFIuB79AJPMO93KaA38Jfii+VPx5JVpURccezKRhKm6l5SQ8+GzYFGDnPpIepIA==
build_script:
- dnvm upgrade
- dnu restore
- dnu publish C:\projects\aspnet5cidemo\src\EmployeeApp\ --configuration Release -o AppOutput --no-source --runtime C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-12103
artifacts:
- path: /AppOutput
  name: AppOutput
test_script:
- dnx.exe C:\projects\aspnet5cidemo\test\project.json test -parallel none
deploy_script:
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp="C:\projects\aspnet5cidemo\AppOutput\wwwroot" -dest:IisApp="ASPNET5CIDemo",ComputerName="%webdeploy_url%",UserName="%webdeploy_user%",Password="%webdeploy_password%",IncludeAcls="False",AuthType="Basic" -enableLink:contentLibExtension -enableRule:DoNotDeleteRule -retryAttempts:2 -enableRule:AppOffline'
 
