version: 1.0.{build}
install:
- ps: '&{$Branch=''dev'';iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1''))}'
build_script:
- %DNX_HOME%\bin\dnvm.cmd upgrade
- %DNX_HOME%\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnu restore
