version: 1.0.{build}
install:
- ps: '&{$Branch=''dev'';iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1''))}'
build_script:
- C:\Users\appveyor\.dnx\bin\dnvm.cmd upgrade
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnu.cmd restore
test_script:
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.exe C:\projects\aspnet5cidemo\test\project.json test -parallel none
before_deploy:
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnu.cmd publish C:\projects\aspnet5cidemo\src\EmployeeApp\ --configuration Release
deploy:
- provider: FTP
  host: 
    secure: UdwCAcFI5EpiHF9g68lvJYhDNAv3uigRGQvlj65Cs2aaytyyrrH6GFXz0H1K4HSKrBpBs1Y5Tk58jbgu9csZAg==
  protocol: ftp
  username: 
    secure: NTg0x11RXPktiHKnL0z3DdxGmTLBnyOgK97uGzRpqNA=
  password:
    secure: QdheUgbmDJBBTyvvw5UPEg==
  folder: /site
  artifact: C:\projects\aspnet5cidemo\src\EmployeeApp\bin\output\*
