version: 1.0.{build}
os: Visual Studio 2015 RC
build_script:
- dnvm upgrade
- dnu restore
- dnu publish C:\projects\aspnet5cidemo\src\EmployeeApp\ --configuration Release -o AppOutput --no-source
artifacts:
- path: /AppOutput
  name: AppOutput
test_script:
- dnx.exe C:\projects\aspnet5cidemo\test\project.json test -parallel none
deploy:
- provider: FTP
  host: 
    secure: MYu+lYxH7APbXHBENDhuSxz059Mdugypy0fKEHlv91iZ2wVYM6HHZ+5KrEn4Kw9V
  protocol: ftp
  username: 
    secure: NTg0x11RXPktiHKnL0z3DdxGmTLBnyOgK97uGzRpqNA=
  password:
    secure: QdheUgbmDJBBTyvvw5UPEg==
  folder: /site
  application: AppOutput
