version: 1.0.{build}
install:
- ps: '&{$Branch=''dev'';iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1''))}'
build_script:
- C:\Users\appveyor\.dnx\bin\dnvm.cmd upgrade
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnu.cmd restore
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnu.cmd publish C:\projects\aspnet5cidemo\src\EmployeeApp\ --configuration Release -o AppOutput --no-source
artifacts:
- path: /AppOutput
  name: AppOutput
test_script:
- C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.exe C:\projects\aspnet5cidemo\test\project.json test -parallel none
deploy:
- provider: FTP
  host: 
    secure: MYu+lYxH7APbXHBENDhuSxz059Mdugypy0fKEHlv91iZ2wVYM6HHZ+5KrEn4Kw9V
  protocol: ftp
  username: 
    secure: NTg0x11RXPktiHKnL0z3DdxGmTLBnyOgK97uGzRpqNA=
  password:
    secure: QdheUgbmDJBBTyvvw5UPEg==
  folder: /site
  application: AppOutput
